"""Construct local npm snapshots from lock-authenticated archives; never execute them.

Only explicitly supplied local material is read. Archive digests bind the resulting
trees to target lockfiles, not to a claim that the target or an advisory feed is
trustworthy. Completion is point-in-time setup evidence, never audit authority.
"""

from __future__ import annotations

import base64
import gzip
import hashlib
import io
import json
import os
import stat
import tarfile
import zlib
from contextlib import suppress
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from mmaudit.config import DependencyPreparationConfig
from mmaudit.isolation import dependencies
from mmaudit.release_io import read_file_evidence, read_json_evidence, write_file_evidence
from mmaudit.repository.secrets import is_sensitive_workspace_path
from mmaudit.scanners.base import (
    retain_scanner_workspace_source_custody,
    scanner_workspace_file_records,
)

_FRAMEWORK_NAMES = frozenset(
    {"hardhat.config.js", "hardhat.config.cjs", "hardhat.config.mjs", "hardhat.config.ts"}
)
_OUTPUT_ROOT = ".mmaudit/managed-dependencies"
_DIRECTORY_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC


class DependencySnapshotBuildError(ValueError):
    """Local snapshot construction failed; incomplete output is never repaired."""


class DependencySnapshotVerificationError(ValueError):
    """Supplied dependency material cannot support a local setup observation."""


class DependencySnapshotBuildLimits(BaseModel):
    """Bound compressed input, expanded tar metadata, individual files and the batch."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    max_projects: int = Field(default=50, ge=1, le=200)
    max_packages: int = Field(default=2000, ge=1, le=10_000)
    max_archive_bytes: int = Field(default=10_000_000, ge=1024, le=64_000_000)
    max_expanded_archive_bytes: int = Field(default=32_000_000, ge=1024, le=100_000_000)
    max_metadata_bytes: int = Field(default=5_000_000, ge=1024, le=20_000_000)
    max_files: int = Field(default=10_000, ge=1, le=100_000)
    max_file_bytes: int = Field(default=5_000_000, ge=1024, le=16_000_000)
    max_total_bytes: int = Field(default=64_000_000, ge=1024, le=256_000_000)


@dataclass(frozen=True, slots=True)
class DependencySnapshotBuildResult:
    """Usable existing-adapter config, without advisory or runtime trust promotion."""

    action: Literal["CREATED", "VERIFIED_EXISTING"]
    config: DependencyPreparationConfig
    project_count: int
    package_count: int
    source_inventory_sha256: str
    advisory_input_sha256: str
    runtime_authority: Literal[False] = field(default=False, init=False)
    managed_run_ready: Literal[False] = field(default=False, init=False)


def build_managed_dependency_snapshot(
    *,
    repository: Path,
    archive_root: Path,
    advisory_path: Path,
    advisory_sha256: str,
    limits: DependencySnapshotBuildLimits | None = None,
    verify_only: bool = False,
) -> DependencySnapshotBuildResult:
    """Build every detected Hardhat root from local SHA-512-addressed tarballs.

    The archive store contains ``<sha512-hex>.tgz`` files, never registry URLs.
    Existing output must match every generated byte; incomplete output is left
    explicit and is not reset, overwritten or treated as a successful repeat.
    """

    try:
        bound = DependencySnapshotBuildLimits() if limits is None else limits
        if type(bound) is not DependencySnapshotBuildLimits or type(verify_only) is not bool:
            raise ValueError("exact limits and boolean verify-only are required")
        bound = DependencySnapshotBuildLimits.model_validate(bound.model_dump(), strict=True)
        root = _canonical_directory(repository)
        archives = _canonical_directory(archive_root)
        if root == archives or root in archives.parents or archives in root.parents:
            raise ValueError("archive store must be separate from the target repository")
        if not dependencies._SHA256.fullmatch(advisory_sha256):
            raise ValueError("an exact supplied advisory digest is required")
        advisory = read_json_evidence(
            evidence_root=advisory_path.parent,
            relative_path=advisory_path.name,
            max_bytes=bound.max_metadata_bytes,
        )
        if advisory.binding.sha256 != advisory_sha256:
            raise ValueError("supplied advisory input digest differs")
        if (
            type(advisory.value) is not dict
            or set(advisory.value) != {"schema_version", "advisories"}
            or advisory.value["schema_version"] != "1.0"
            or type(advisory.value["advisories"]) is not list
            or len(advisory.value["advisories"]) > 20_000
        ):
            raise ValueError("supplied advisory input has an unsupported shape")
        source = retain_scanner_workspace_source_custody(root)
        try:
            source_sha256 = source.source_inventory_sha256_before
            snapshot, files, package_count = _construct_snapshot(
                root, archives, advisory.value["advisories"], bound
            )
            snapshot_bytes = _json_bytes(snapshot.model_dump(mode="json"))
            if len(snapshot_bytes) > bound.max_metadata_bytes:
                raise ValueError("generated snapshot exceeds its metadata limit")
            provenance = _json_bytes(
                {
                    "schema_version": "1.0",
                    "artifact_kind": "local-archive-authenticated-dependency-material",
                    "source_inventory_sha256": source_sha256,
                    "advisory_input_sha256": advisory_sha256,
                    "advisory_freshness_verified": False,
                    "advisory_completeness_verified": False,
                    "runtime_authority": False,
                    "managed_run_ready": False,
                }
            )
            build_sha256 = hashlib.sha256(snapshot_bytes + provenance).hexdigest()
            relative = f"{_OUTPUT_ROOT}/{build_sha256}"
            config = DependencyPreparationConfig(
                enabled=True,
                required=True,
                offline_snapshot_path=f"{relative}/snapshot.json",
                offline_snapshot_sha256=hashlib.sha256(snapshot_bytes).hexdigest(),
                max_snapshot_bytes=bound.max_metadata_bytes,
                max_projects=bound.max_projects,
                max_packages=bound.max_packages,
                max_files=bound.max_files,
                max_file_bytes=bound.max_file_bytes,
                max_total_bytes=bound.max_total_bytes,
            )
            files["provenance.json"] = provenance
            files["dependencies.toml"] = _config_toml(config)
            files["snapshot.json"] = snapshot_bytes
            if source.finalize() != source_sha256:
                raise ValueError("target changed during dependency construction")
        finally:
            source.close()
        action = _publish_or_verify(root, relative, files, verify_only=verify_only)
        return DependencySnapshotBuildResult(
            action=action,
            config=config,
            project_count=len(snapshot.projects),
            package_count=package_count,
            source_inventory_sha256=source_sha256,
            advisory_input_sha256=advisory_sha256,
        )
    except (
        OSError,
        ValueError,
        TypeError,
        KeyError,
        EOFError,
        RecursionError,
        OverflowError,
        tarfile.TarError,
        zlib.error,
    ) as exc:
        raise DependencySnapshotBuildError(
            "Local dependency snapshot refused; no authority granted. "
            "Any incomplete output is preserved and must not be consumed."
        ) from exc


def verify_managed_dependency_snapshot(
    *, repository: Path, config: DependencyPreparationConfig
) -> str:
    """Verify pinned private material against all local Hardhat locks, without writes.

    The caller must retain and finalize target custody around this observation.
    This checks supplied trees and exact-version advisories, not original archives,
    feed freshness/completeness, installed tools, or future execution authority.
    """

    try:
        if type(config) is not DependencyPreparationConfig:
            raise ValueError("exact dependency configuration is required")
        selected = DependencyPreparationConfig.model_validate(config.model_dump(), strict=True)
        if not selected.enabled or selected.offline_snapshot_path is None:
            raise ValueError("dependency snapshot is not configured")
        root = _canonical_directory(repository)
        relative = _canonical_member_path(selected.offline_snapshot_path)
        limits = DependencySnapshotBuildLimits(
            max_metadata_bytes=selected.max_snapshot_bytes,
            max_projects=selected.max_projects,
            max_packages=selected.max_packages,
            max_files=min(selected.max_files, 100_000),
            max_file_bytes=min(selected.max_file_bytes, 16_000_000),
            max_total_bytes=min(selected.max_total_bytes, 256_000_000),
        )
        raw = read_json_evidence(
            evidence_root=root, relative_path=relative, max_bytes=limits.max_metadata_bytes
        )
        if raw.binding.sha256 != selected.offline_snapshot_sha256:
            raise ValueError("snapshot differs from its configured digest")
        snapshot = dependencies._DependencySnapshot.model_validate_json(raw.content, strict=True)
        original = _strict_object(raw.content)
        advised_versions: dict[str, set[str]] = {}
        for advisory in snapshot.advisories:
            advised_versions.setdefault(advisory.package_name, set()).update(advisory.versions)
        roots = _project_roots(root)
        if len(roots) > limits.max_projects or roots != [p.project_root for p in snapshot.projects]:
            raise ValueError("snapshot does not cover the exact detected Hardhat project set")
        budget = _MaterialBudget(limits)
        snapshot_identity = _material_identity((root / relative).lstat())
        metadata_bytes = len(raw.content)
        package_count = 0
        sources: set[str] = set()
        for project, raw_project in zip(snapshot.projects, original["projects"], strict=True):
            if project.project_root != raw_project["project_root"]:
                raise ValueError("snapshot project path was normalized")
            prefix = (
                ""
                if project.project_root == "."
                else _canonical_member_path(project.project_root) + "/"
            )
            manifest = read_json_evidence(
                evidence_root=root,
                relative_path=prefix + "package.json",
                max_bytes=min(limits.max_metadata_bytes, dependencies._MAX_PACKAGE_JSON_BYTES),
            )
            dependencies._reject_lifecycle_scripts(_strict_object(manifest.content), checks={})
            lock = read_json_evidence(
                evidence_root=root,
                relative_path=prefix + "package-lock.json",
                max_bytes=limits.max_metadata_bytes,
            )
            metadata_bytes += len(manifest.content) + len(lock.content)
            if metadata_bytes > limits.max_total_bytes:
                raise ValueError("aggregate target metadata exceeds its bound")
            if lock.binding.sha256 != project.lockfile_sha256:
                raise ValueError("target lockfile differs from the snapshot")
            locked = _validated_lock_packages(lock.content, limits.max_packages)
            if set(locked) != {p.lock_path for p in project.packages}:
                raise ValueError("snapshot package set differs from the exact target lock")
            for package, raw_package in zip(project.packages, raw_project["packages"], strict=True):
                package_count += 1
                if package_count > limits.max_packages:
                    raise ValueError("aggregate package count exceeds its bound")
                if any(
                    getattr(package, key) != raw_package[key] for key in ("source", "lock_path")
                ):
                    raise ValueError("snapshot package path was normalized")
                _canonical_member_path(package.lock_path)
                _canonical_member_path(package.source)
                if package.source in sources:
                    raise ValueError("package sources must be unique across all projects")
                sources.add(package.source)
                entry = locked[package.lock_path]
                dependencies._lock_integrity(entry)
                if (
                    entry.get("version") != package.version
                    or dependencies._npm_name_from_lock_path(package.lock_path) != package.name
                    or entry.get("hasInstallScript")
                    or entry.get("link")
                ):
                    raise ValueError("snapshot package differs from an inert exact lock entry")
                directory = _private_directories(
                    root, str(PurePosixPath(relative).parent / package.source), create=False
                )
                material = _read_material_tree(directory, budget)
                package_json = _strict_object(material["package.json"])
                if (
                    package_json.get("name") != package.name
                    or package_json.get("version") != package.version
                ):
                    raise ValueError("package manifest identity differs")
                dependencies._reject_lifecycle_scripts(package_json, checks={})
                tree = hashlib.sha256(b"mmaudit-dependency-tree-v1\0")
                for path, content in sorted(material.items()):
                    tree.update(
                        path.encode("utf-8") + b"\0" + hashlib.sha256(content).digest() + b"\0"
                    )
                if tree.hexdigest() != package.tree_sha256:
                    raise ValueError("package contents differ from the pinned snapshot")
                if package.version in advised_versions.get(package.name, set()):
                    raise ValueError("supplied advisory matches a dependency version")
        for material_path, identity in budget.identities.items():
            if _material_identity(material_path.lstat()) != identity:
                raise ValueError("dependency tree changed during the aggregate observation")
        final_snapshot = read_file_evidence(
            evidence_root=root, relative_path=relative, max_bytes=limits.max_metadata_bytes
        )
        if (
            final_snapshot.content != raw.content
            or _material_identity((root / relative).lstat()) != snapshot_identity
        ):
            raise ValueError("snapshot changed during material verification")
        return raw.binding.sha256
    except (OSError, ValueError, TypeError, KeyError, RecursionError, OverflowError) as exc:
        raise DependencySnapshotVerificationError(
            "Supplied dependency material failed local verification; no authority granted."
        ) from exc


@dataclass(slots=True)
class _MaterialBudget:
    limits: DependencySnapshotBuildLimits
    files: int = 0
    directories: int = 0
    total_bytes: int = 0
    identities: dict[Path, tuple[int, ...]] = field(default_factory=dict)


def _material_identity(metadata: os.stat_result) -> tuple[int, ...]:
    return (
        metadata.st_dev,
        metadata.st_ino,
        metadata.st_mode,
        metadata.st_nlink,
        metadata.st_uid,
        metadata.st_gid,
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    )


def _read_material_tree(directory: Path, budget: _MaterialBudget) -> dict[str, bytes]:
    """Read bounded private inert files, then recheck the complete observed tree."""

    files: dict[str, bytes] = {}

    def visit(current: int, prefix: str) -> None:
        with os.scandir(current) as entries:
            for entry in entries:
                path = _canonical_member_path(prefix + entry.name)
                if is_sensitive_workspace_path(path) or "node_modules" in PurePosixPath(path).parts:
                    raise ValueError("dependency material contains a sensitive or unmanaged path")
                metadata = os.stat(entry.name, dir_fd=current, follow_symlinks=False)
                budget.identities[directory / path] = _material_identity(metadata)
                if stat.S_ISDIR(metadata.st_mode):
                    budget.directories += 1
                    if budget.directories > budget.limits.max_files * 32:
                        raise ValueError("dependency directory inventory exceeds its bound")
                    child = os.open(entry.name, _DIRECTORY_FLAGS, dir_fd=current)
                    try:
                        _private_metadata(child)
                        visit(child, path + "/")
                    finally:
                        os.close(child)
                else:
                    budget.files += 1
                    budget.total_bytes += metadata.st_size
                    if (
                        not stat.S_ISREG(metadata.st_mode)
                        or stat.S_IMODE(metadata.st_mode) != 0o600
                        or metadata.st_uid != os.geteuid()
                        or metadata.st_nlink != 1
                        or budget.files > budget.limits.max_files
                        or budget.total_bytes > budget.limits.max_total_bytes
                    ):
                        raise ValueError("dependency files are unsafe or exceed their bounds")
                    content = read_file_evidence(
                        evidence_root=directory,
                        relative_path=path,
                        max_bytes=min(
                            budget.limits.max_file_bytes, dependencies._MAX_PACKAGE_JSON_BYTES
                        )
                        if path == "package.json"
                        else budget.limits.max_file_bytes,
                    ).content
                    if _material_identity(metadata) != _material_identity(
                        os.stat(entry.name, dir_fd=current, follow_symlinks=False)
                    ):
                        raise ValueError("dependency file metadata changed during its read")
                    dependencies.validate_inert_dependency_file(path, metadata.st_mode, content)
                    files[path] = content

    descriptor = os.open(directory, _DIRECTORY_FLAGS)
    try:
        identity = _private_metadata(descriptor)
        budget.identities[directory] = _material_identity(os.fstat(descriptor))
        visit(descriptor, "")
        _verify_output(directory, descriptor, files)
        current = os.open(_canonical_directory(directory), _DIRECTORY_FLAGS)
        try:
            if _private_metadata(current) != identity:
                raise ValueError("dependency package root changed during verification")
        finally:
            os.close(current)
    finally:
        os.close(descriptor)
    return files


def _validated_lock_packages(content: bytes, max_packages: int) -> dict[str, dict[str, object]]:
    value = _strict_object(content)
    if type(value.get("lockfileVersion")) is not int or type(value.get("packages")) is not dict:
        raise ValueError("lockfile requires an integer version and an exact packages map")
    raw_packages = value["packages"]
    if len(raw_packages) > max_packages + 1:
        raise ValueError("raw lock package map exceeds its bound")
    # Check raw keys before the legacy parser normalizes them into dictionary keys.
    for raw_path in raw_packages:
        if raw_path:
            _canonical_member_path(raw_path)
    return dependencies._load_lock_packages(content, max_packages)


def _project_roots(repository: Path) -> list[str]:
    return sorted(
        {
            str(PurePosixPath(record.relative_path).parent)
            for record in scanner_workspace_file_records(repository)
            if PurePosixPath(record.relative_path).name in _FRAMEWORK_NAMES
        }
    )


def _construct_snapshot(
    repository: Path,
    archives: Path,
    advisory_records: list[Any],
    limits: DependencySnapshotBuildLimits,
) -> tuple[dependencies._DependencySnapshot, dict[str, bytes], int]:
    project_roots = _project_roots(repository)
    if not 1 <= len(project_roots) <= limits.max_projects:
        raise ValueError("complete Hardhat project set is absent or exceeds its bound")
    projects: list[dict[str, Any]] = []
    files: dict[str, bytes] = {}
    decoded_archives: dict[str, dict[str, bytes]] = {}
    total_files = total_bytes = total_packages = total_compressed = total_expanded = 0
    for project_root in project_roots:
        prefix = "" if project_root == "." else project_root + "/"
        manifest = read_json_evidence(
            evidence_root=repository,
            relative_path=prefix + "package.json",
            max_bytes=min(limits.max_metadata_bytes, dependencies._MAX_PACKAGE_JSON_BYTES),
        )
        if type(manifest.value) is not dict:
            raise ValueError("project manifest is not an object")
        dependencies._reject_lifecycle_scripts(dict(manifest.value), checks={})
        lock = read_json_evidence(
            evidence_root=repository,
            relative_path=prefix + "package-lock.json",
            max_bytes=limits.max_metadata_bytes,
        )
        locked = _validated_lock_packages(lock.content, limits.max_packages)
        packages: list[dict[str, str]] = []
        for lock_path, entry in sorted(locked.items()):
            _canonical_member_path(lock_path)
            name = dependencies._npm_name_from_lock_path(lock_path)
            integrity = dependencies._lock_integrity(entry)
            digest = base64.b64decode(integrity.removeprefix("sha512-"), validate=True)
            version = entry.get("version")
            if not isinstance(version, str) or not dependencies._VERSION.fullmatch(version):
                raise ValueError("package version must be exact")
            if entry.get("hasInstallScript") or entry.get("link"):
                raise ValueError("locked lifecycle or linked packages are unsupported")
            key = digest.hex()
            if key not in decoded_archives:
                archive = read_file_evidence(
                    evidence_root=archives,
                    relative_path=f"{key}.tgz",
                    max_bytes=limits.max_archive_bytes,
                ).content
                total_compressed += len(archive)
                if total_compressed > limits.max_total_bytes:
                    raise ValueError("aggregate compressed input exceeds its bound")
                if hashlib.sha512(archive).digest() != digest:
                    raise ValueError("archive SHA-512 differs from the target lockfile")
                material, expanded_size = _unpack_archive(archive, limits)
                total_expanded += expanded_size
                if total_expanded > limits.max_total_bytes:
                    raise ValueError("aggregate expanded archive input exceeds its bound")
                decoded_archives[key] = material
            material = decoded_archives[key]
            package_json = _strict_object(material["package.json"])
            if package_json.get("name") != name or package_json.get("version") != version:
                raise ValueError("archive package identity differs from its target lock entry")
            dependencies._reject_lifecycle_scripts(package_json, checks={})
            total_packages += 1
            total_files += len(material)
            total_bytes += sum(len(value) for value in material.values())
            if (
                total_packages > limits.max_packages
                or total_files > limits.max_files
                or total_bytes > limits.max_total_bytes
            ):
                raise ValueError("aggregate dependency material exceeds its bound")
            tree = hashlib.sha256(b"mmaudit-dependency-tree-v1\0")
            slot = hashlib.sha256(f"{project_root}\0{lock_path}".encode()).hexdigest()
            package_source = f"packages/{key}-{slot}"
            for path, content in sorted(material.items()):
                tree.update(path.encode("utf-8") + b"\0" + hashlib.sha256(content).digest() + b"\0")
                files[f"{package_source}/{path}"] = content
            packages.append(
                {
                    "lock_path": lock_path,
                    "name": name,
                    "version": version,
                    "source": package_source,
                    "tree_sha256": tree.hexdigest(),
                }
            )
        projects.append(
            {
                "project_root": project_root,
                "lockfile": "package-lock.json",
                "lockfile_sha256": lock.binding.sha256,
                "packages": packages,
            }
        )
    snapshot = dependencies._DependencySnapshot.model_validate_json(
        _json_bytes(
            {"schema_version": "1.0", "projects": projects, "advisories": advisory_records}
        ),
        strict=True,
    )
    return snapshot, files, total_packages


def _unpack_archive(
    content: bytes, limits: DependencySnapshotBuildLimits
) -> tuple[dict[str, bytes], int]:
    with gzip.GzipFile(fileobj=io.BytesIO(content)) as compressed:
        expanded = compressed.read(limits.max_expanded_archive_bytes + 1)
    if len(expanded) > limits.max_expanded_archive_bytes:
        raise ValueError("archive expansion exceeds its bound")
    files: dict[str, bytes] = {}
    seen: set[str] = set()
    total_bytes = 0
    with tarfile.open(fileobj=io.BytesIO(expanded), mode="r:") as archive:
        for index, member in enumerate(archive):
            if index >= limits.max_files * 2 or member.pax_headers or member.issparse():
                raise ValueError("archive metadata is unsupported or exceeds its bound")
            name = member.name.rstrip("/") if member.isdir() else member.name
            if name == "package" and member.isdir():
                continue
            path = _canonical_member_path(name)
            if not path.startswith("package/"):
                raise ValueError("archive member is outside the package prefix")
            relative = path.removeprefix("package/")
            if relative in seen or is_sensitive_workspace_path(relative, is_dir=member.isdir()):
                raise ValueError("archive has duplicate or sensitive members")
            seen.add(relative)
            if member.isdir():
                continue
            if not member.isfile() or member.mode & 0o7000:
                raise ValueError("archive contains links, devices or special permissions")
            if not 0 <= member.size <= limits.max_file_bytes:
                raise ValueError("archive file exceeds its bound")
            total_bytes += member.size
            if len(files) >= limits.max_files or total_bytes > limits.max_total_bytes:
                raise ValueError("archive material exceeds its aggregate bound")
            stream = archive.extractfile(member)
            if stream is None:
                raise ValueError("archive member cannot be read")
            with stream:
                data = stream.read(member.size + 1)
            if len(data) != member.size:
                raise ValueError("archive member is truncated")
            dependencies.validate_inert_dependency_file(relative, member.mode, data)
            files[relative] = data
        trailing = expanded[archive.offset :]
        if len(expanded) % 512 or len(trailing) < 1024 or any(trailing):
            raise ValueError("archive has missing end markers or unaccounted trailing bytes")
    if (
        "package.json" not in files
        or len(files["package.json"]) > dependencies._MAX_PACKAGE_JSON_BYTES
    ):
        raise ValueError("archive lacks a bounded package manifest")
    # Nested node_modules must come from their own lock entries, never hidden payloads.
    if any("node_modules" in PurePosixPath(path).parts for path in files):
        raise ValueError("archive embeds unmanaged node_modules material")
    for path in files:
        if any(str(parent) in files for parent in PurePosixPath(path).parents):
            raise ValueError("archive file and directory paths conflict")
    return files, len(expanded)


def _canonical_member_path(value: str) -> str:
    if (
        len(value) > 500
        or len(value.split("/")) > 32
        or any(part in {"", ".", ".."} for part in value.split("/"))
        or dependencies._safe_relative(value) != value
    ):
        raise ValueError("archive or lock path is not canonical and bounded")
    return value


def _strict_object(content: bytes) -> dict[str, Any]:
    def pairs(items: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, item in items:
            if key in value:
                raise ValueError("duplicate JSON key")
            value[key] = item
        return value

    def nonfinite(_value: str) -> None:
        raise ValueError("non-finite JSON")

    value = json.loads(content, object_pairs_hook=pairs, parse_constant=nonfinite)
    if type(value) is not dict:
        raise ValueError("package manifest must be an object")
    return value


def _json_bytes(value: object) -> bytes:
    return (json.dumps(value, sort_keys=True, indent=2, allow_nan=False) + "\n").encode("utf-8")


def _config_toml(config: DependencyPreparationConfig) -> bytes:
    lines = [
        "# Generated offline dependency input; not runtime or audit authority.",
        "[dependency_preparation]",
    ]
    for key, value in config.model_dump(mode="json").items():
        lines.append(f"{key} = {json.dumps(value)}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _canonical_directory(path: Path) -> Path:
    if not path.is_absolute() or path != path.resolve(strict=True) or not path.is_dir():
        raise ValueError("local input root must be an absolute unlinked directory")
    return path


def _private_metadata(descriptor: int) -> tuple[int, int]:
    metadata = os.fstat(descriptor)
    if (
        not stat.S_ISDIR(metadata.st_mode)
        or stat.S_IMODE(metadata.st_mode) != 0o700
        or metadata.st_uid != os.geteuid()
    ):
        raise ValueError("dependency output directory must be private and owned")
    return metadata.st_dev, metadata.st_ino


def _private_directories(root: Path, relative: str, *, create: bool) -> Path:
    descriptor = os.open(root, _DIRECTORY_FLAGS)
    try:
        for part in PurePosixPath(relative).parts:
            if create:
                with suppress(FileExistsError):
                    os.mkdir(part, 0o700, dir_fd=descriptor)
            child = os.open(part, _DIRECTORY_FLAGS, dir_fd=descriptor)
            try:
                _private_metadata(child)
            except BaseException:
                os.close(child)
                raise
            os.close(descriptor)
            descriptor = child
        return root / relative
    finally:
        os.close(descriptor)


def _publish_or_verify(
    repository: Path, relative: str, files: dict[str, bytes], *, verify_only: bool
) -> Literal["CREATED", "VERIFIED_EXISTING"]:
    parent = _private_directories(repository, _OUTPUT_ROOT, create=not verify_only)
    parent_fd = os.open(parent, _DIRECTORY_FLAGS)
    try:
        _private_metadata(parent_fd)
        name = PurePosixPath(relative).name
        created = False
        if not verify_only:
            try:
                os.mkdir(name, 0o700, dir_fd=parent_fd)
                created = True
            except FileExistsError:
                pass
        directory = parent / name
        descriptor = os.open(name, _DIRECTORY_FLAGS, dir_fd=parent_fd)
        try:
            identity = _private_metadata(descriptor)
            if created:
                # The consumer's manifest is written last; partial output is not a snapshot.
                for path in sorted(files, key=lambda item: (item == "snapshot.json", item)):
                    subdirectory = str(PurePosixPath(path).parent)
                    if subdirectory != ".":
                        _private_directories(directory, subdirectory, create=True)
                    write_file_evidence(
                        evidence_root=directory,
                        relative_path=path,
                        content=files[path],
                        max_bytes=max(len(files[path]), 1),
                    )
                os.fsync(descriptor)
                os.fsync(parent_fd)
            _verify_output(directory, descriptor, files)
            entry = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
            if (entry.st_dev, entry.st_ino) != identity:
                raise ValueError("dependency output directory identity changed")
            check = os.open(repository / relative, _DIRECTORY_FLAGS)
            try:
                if _private_metadata(check) != identity:
                    raise ValueError("dependency output path changed")
            finally:
                os.close(check)
        finally:
            os.close(descriptor)
    finally:
        os.close(parent_fd)
    return "CREATED" if created else "VERIFIED_EXISTING"


def _verify_output(directory: Path, descriptor: int, files: dict[str, bytes]) -> None:
    expected_directories = {
        str(parent)
        for path in files
        for parent in PurePosixPath(path).parents
        if str(parent) != "."
    }
    seen_files: set[str] = set()
    seen_directories: set[str] = set()

    def visit(current: int, prefix: str) -> None:
        with os.scandir(current) as entries:
            for entry in entries:
                path = prefix + entry.name
                if entry.is_dir(follow_symlinks=False):
                    if path not in expected_directories:
                        raise ValueError("unexpected dependency output directory")
                    child = os.open(entry.name, _DIRECTORY_FLAGS, dir_fd=current)
                    try:
                        _private_metadata(child)
                        seen_directories.add(path)
                        visit(child, path + "/")
                    finally:
                        os.close(child)
                else:
                    if path not in files:
                        raise ValueError("unexpected dependency output file")
                    metadata = os.stat(entry.name, dir_fd=current, follow_symlinks=False)
                    if stat.S_IMODE(metadata.st_mode) != 0o600 or metadata.st_uid != os.geteuid():
                        raise ValueError("dependency output file must remain private and owned")
                    observed = read_file_evidence(
                        evidence_root=directory,
                        relative_path=path,
                        max_bytes=max(len(files[path]), 1),
                    ).content
                    if observed != files[path]:
                        raise ValueError("existing dependency output differs")
                    seen_files.add(path)

    visit(descriptor, "")
    if seen_files != set(files) or seen_directories != expected_directories:
        raise ValueError("existing dependency output is incomplete")
